### ISSUE TITLE
Update 1.1

### ISSUE THREAD

**Issue by exwundee** [exwundee/PartyChat#1]
- [x] Change `/party chat` to `/party toggle`.
- [x] Change `/party info` to `/party list`.
- [x] Add `/party kick <player>`.
- [x] Add `/party disband`.
- [x] Add `/party transfer <player>`.
- [x] Party auto disbands when the host disconnects.
- [x] Add `/adminparty spy`
- [x] Add `/adminparty show <player>` (Shows what party the selected player is in, if any)
- [x] Fix "null has joined the party!"
- [x] Add expiration time to inviting the same player. (120 seconds)
- [x] Reformatting messages.

**Comment by exwundee** [comment]
Could not pass event PlayerQuitEvent to PartyChat v1.0
java.lang.NullPointerException: Cannot invoke "org.bukkit.entity.Player.equals(Object)" because the return value of "java.util.HashMap.get(Object)" is null
        at com.exwundee.partychat.PartyChat.onLeave(PartyChat.java:60) ~[PartyChat.jar:?]

Putting this here to reference a bug later before release.

**Comment by exwundee** [comment]
> Could not pass event PlayerQuitEvent to PartyChat v1.0 java.lang.NullPointerException: Cannot invoke "org.bukkit.entity.Player.equals(Object)" because the return value of "java.util.HashMap.get(Object)" is null at com.exwundee.partychat.PartyChat.onLeave(PartyChat.java:60) ~[PartyChat.jar:?]
> 
> Putting this here to reference a bug later before release.

This has now been fixed.
