### ISSUE TITLE
UnsupportedOperationException

### ISSUE THREAD

**Issue by exwundee** [exwundee/PartyChat#5]
[19:30:02 INFO]: Player issued server command: /party invite x1D
[19:30:02 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'party' in plugin PartyChat v1.1
    at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[folia-api-1.20.4-R0.1-SNAPSHOT.jar:?]
    at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:155) ~[folia-api-1.20.4-R0.1-SNAPSHOT.jar:?]
    at org.bukkit.craftbukkit.v1_20_R3.CraftServer.dispatchCommand(CraftServer.java:1042) ~[folia-1.20.4.jar:git-Folia-"e97b1ee"]
    at org.bukkit.craftbukkit.v1_20_R3.command.BukkitCommandWrapper.run(BukkitCommandWrapper.java:64) ~[folia-1.20.4.jar:git-Folia-"e97b1ee"]
    at com.mojang.brigadier.context.ContextChain.runExecutable(ContextChain.java:73) ~[brigadier-1.2.9.jar:?]
    at net.minecraft.commands.execution.tasks.ExecuteCommand.execute(ExecuteCommand.java:32) ~[folia-1.20.4.jar:git-Folia-"e97b1ee"]
    at net.minecraft.commands.execution.tasks.ExecuteCommand.execute(ExecuteCommand.java:19) ~[folia-1.20.4.jar:git-Folia-"e97b1ee"]
    at net.minecraft.commands.execution.UnboundEntryAction.lambda$bind$0(UnboundEntryAction.java:8) ~[folia-1.20.4.jar:git-Folia-"e97b1ee"]
    at net.minecraft.commands.execution.CommandQueueEntry.a(CommandQueueEntry.java:5) ~[folia-1.20.4.jar:git-Folia-"e97b1ee"]
    at net.minecraft.commands.execution.ExecutionContext.runCommandQueue(ExecutionContext.java:101) ~[folia-1.20.4.jar:git-Folia-"e97b1ee"]
    at net.minecraft.commands.Commands.executeCommandInContext(Commands.java:434) ~[?:?]
    at net.minecraft.commands.Commands.performCommand(Commands.java:336) ~[?:?]
    at net.minecraft.commands.Commands.performCommand(Commands.java:323) ~[?:?]
    at net.minecraft.server.network.ServerGamePacketListenerImpl.performChatCommand(ServerGamePacketListenerImpl.java:2285) ~[?:?]
    at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChatCommand$14(ServerGamePacketListenerImpl.java:2245) ~[?:?]
    at io.papermc.paper.threadedregions.EntityScheduler.executeTick(EntityScheduler.java:173) ~[folia-1.20.4.jar:git-Folia-"e97b1ee"]
    at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1636) ~[folia-1.20.4.jar:git-Folia-"e97b1ee"]
    at io.papermc.paper.threadedregions.TickRegions$ConcreteRegionTickHandle.tickRegion(TickRegions.java:407) ~[folia-1.20.4.jar:git-Folia-"e97b1ee"]
    at io.papermc.paper.threadedregions.TickRegionScheduler$RegionScheduleHandle.runTick(TickRegionScheduler.java:404) ~[folia-1.20.4.jar:git-Folia-"e97b1ee"]
    at ca.spottedleaf.concurrentutil.scheduler.SchedulerThreadPool$TickThreadRunner.run(SchedulerThreadPool.java:525) ~[folia-1.20.4.jar:git-Folia-"e97b1ee"]
    at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.UnsupportedOperationException
    at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftScheduler.handle(CraftScheduler.java:535) ~[folia-1.20.4.jar:git-Folia-"e97b1ee"]
    at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftScheduler.runTaskTimer(CraftScheduler.java:235) ~[folia-1.20.4.jar:git-Folia-"e97b1ee"]
    at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftScheduler.runTaskTimer(CraftScheduler.java:211) ~[folia-1.20.4.jar:git-Folia-"e97b1ee"]
    at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftScheduler.runTaskLater(CraftScheduler.java:175) ~[folia-1.20.4.jar:git-Folia-"e97b1ee"]
    at com.exwundee.partychat.PartyChat.onCommand(PartyChat.java:194) ~[PartyChat-folia.jar:?]
    at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[folia-api-1.20.4-R0.1-SNAPSHOT.jar:?]
    ... 20 more

**Comment by exwundee** [comment]
This error was using the Folia version of this plugin, could be a Folia issue?

**Comment by exwundee** [comment]
Folia is currently not fully supported, so this will be closed for now.
